### ISSUE TITLE
Did I show up at a bad time?

### ISSUE THREAD

**Issue by davidgumberg** [fabioiop/MBP-2010-GPU-Panic-fix#1]
Damn, i happened to need this script today, are the files in the release section working?

**Comment by fabioiop** [comment]
Hi,
Yes. Download the app (.zip) and run it.

**Comment by heyitzaamir** [comment]
Hey everytime I run it, it tells me to boot my laptop?

**Comment by fabioiop** [comment]
After complete the fix process, the macOS reboot will be necessary.

**Comment by heyitzaamir** [comment]
does the patch work if I use an external monitor? just wondering

**Comment by fabioiop** [comment]
Internal lcd only. External monitor needs to replace the bad capacitor.

**Comment by davidgumberg** [comment]
master branch has no source is what i meant by this issue, sorry if i was unclear
