### ISSUE TITLE
Crash frequently

### ISSUE THREAD

**Issue by leoho-HFC** [fabioiop/MBP-2010-GPU-Panic-fix#12]
Hi Support,

I have just upgraded my compute macOS to Ventura 10.13.4 and tried to apply MBP-2010 GPUPanicFix.dmg,  The computer still continues to crash frequently.  Any idea I need to do additionally.

Regards,
Leo

**Comment by fabioiop** [comment]
Hi, read the comments: [https://github.com/fabioiop/MBP-2010-GPU-Panic-fix/issues/10#issuecomment-1443188083](https://github.com/fabioiop/MBP-2010-GPU-Panic-fix/issues/10#issuecomment-1443188083)
