### ISSUE TITLE
macOS Sonoma with OCLP

### ISSUE THREAD

**Issue by taikun114** [fabioiop/MBP-2010-GPU-Panic-fix#13]
On macOS Sonoma with OCLP, I was unable to boot macOS using the instructions in #10 (it worked fine on Ventura with OCLP 1.0.1).
When attempting to boot the OS, it displays a prohibited symbol (https://support.apple.com/en-us/101666). This happens with both the USB installer and the installed OS.

Is there any way to prevent GPU Panic from happening on Sonoma?

**Comment by fabioiop** [comment]
no support

**Comment by taikun114** [comment]
I see, I understand.

Thank you for responding!
