### ISSUE TITLE
GPU Panic when external monitor connected

### ISSUE THREAD

**Issue by vaisko** [fabioiop/MBP-2010-GPU-Panic-fix#14]
First of all, thank you Fabio for your excellent work.

The fix works wonders for me, but I still get crashes when I have an external monitor connected.

Not sure if you're aware of this.

Merry Christmas!
Vaisko

Panic report is below:

`Anonymous UUID:       21502DEF-86D4-03E6-FE3C-3C38763979C2

Mon Dec 25 14:09:35 2023

*** Panic Report ***
panic(cpu 2 caller 0xffffff7f983bf8d3): "GPU Panic: mux-regs 3 3 7f 0 0 0 severity 3 WS-ready 1 switch-state 0 IG FBs 0 EG FBs 3:3 power-state 0 3D idle HDA idle system-state 1 power-level 20:20 connect-change 0 : NVRM[0/1:0:0]: Read Error 0x00000100: CFG 0xffffffff 0xffffffff 0xffffffff, BAR0 0xd2000000 0xffffff913583e000 0x0a5480a2, D0, P2/4\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGraphicsControl/AppleGraphicsControl-3.20.18/src/AppleMuxControl/kext/GPUPanic.cpp:170
Backtrace (CPU 2), Frame : Return Address
0xffffff912402a960 : 0xffffff801706ae76 
0xffffff912402a9b0 : 0xffffff8017194484 
0xffffff912402a9f0 : 0xffffff8017186654 
0xffffff912402aa60 : 0xffffff801701ce60 
0xffffff912402aa80 : 0xffffff801706a8ec 
0xffffff912402abb0 : 0xffffff801706a6ac 
0xffffff912402ac10 : 0xffffff7f983bf8d3 
0xffffff912402ac70 : 0xffffff7f98f02441 
0xffffff912402ad30 : 0xffffff7f98fce1ca 
0xffffff912402ad70 : 0xffffff7f98fce235 
0xffffff912402adf0 : 0xffffff7f9a07b7f0 
0xffffff912402af10 : 0xffffff7f98fefd35 
0xffffff912402af30 : 0xffffff7f98f09048 
0xffffff912402afe0 : 0xffffff7f98f06a84 
0xffffff912402b1d0 : 0xffffff7f98f084c1 
0xffffff912402b2a0 : 0xffffff7f99184a27 
0xffffff912402b3f0 : 0xffffff7f9917a013 
0xffffff912402b6e0 : 0xffffff7f99131136 
0xffffff912402b720 : 0xffffff7f9917e669 
0xffffff912402b790 : 0xffffff7f991674bb 
0xffffff912402b800 : 0xffffff7f99167db1 
0xffffff912402b850 : 0xffffff7f991681e4 
0xffffff912402b8b0 : 0xffffff7f991688ea 
0xffffff912402b8f0 : 0xffffff7f99137e03 
0xffffff912402ba70 : 0xffffff7f991367cb 
0xffffff912402bad0 : 0xffffff80176c2878 
0xffffff912402bb20 : 0xffffff80176c0be6 
0xffffff912402bb70 : 0xffffff80176c9667 
0xffffff912402bcb0 : 0xffffff80171417e4 
0xffffff912402bdc0 : 0xffffff8017070380 
0xffffff912402be10 : 0xffffff801704d6ed 
0xffffff912402be60 : 0xffffff80170601fb 
0xffffff912402bef0 : 0xffffff801717033d 
0xffffff912402bfa0 : 0xffffff801701d666 
      Kernel Extensions in backtrace:
         com.apple.nvidia.classic.NVDAResmanTesla(10.0.4)[F8258F0F-61AD-30F4-BDD5-B18CCAAE535A]@0xffffff7f98eb1000->0xffffff7f99119fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[F763C275-306F-358F-B6B0-0FD93486BD5F]@0xffffff7f97894000
            dependency: com.apple.iokit.IONDRVSupport(519.21)[B9EB0174-55E4-3CB1-9802-E74BB1BD5EF0]@0xffffff7f98389000
            dependency: com.apple.iokit.IOGraphicsFamily(519.23)[81D774E8-DD11-3866-B90A-E855215EDB60]@0xffffff7f9804d000
         com.apple.nvidia.classic.NVDANV50HalTesla(10.0.4)[5DCF031B-F81F-32A3-ADCD-18E16EAC7CF0]@0xffffff7f99f57000->0xffffff7f9a1fffff
            dependency: com.apple.nvidia.classic.NVDAResmanTesla(10.0.4)[F8258F0F-61AD-30F4-BDD5-B18CCAAE535A]@0xffffff7f98eb1000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[F763C275-306F-358F-B6B0-0FD93486BD5F]@0xffffff7f97894000
         com.apple.driver.AppleMuxControl(3.20.18)[F7F686D3-0917-3DF0-B1BE-A002B920B866]@0xffffff7f983b1000->0xffffff7f983c3fff
            dependency: com.apple.driver.AppleGraphicsControl(3.20.18)[EA19739D-41D6-374F-AEC4-80CFB300B7D6]@0xffffff7f98372000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[95DA39BB-7C39-3742-A2E5-86C555E21D67]@0xffffff7f97db3000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[F763C275-306F-358F-B6B0-0FD93486BD5F]@0xffffff7f97894000
            dependency: com.apple.iokit.IOGraphicsFamily(519.23)[81D774E8-DD11-3866-B90A-E855215EDB60]@0xffffff7f9804d000
            dependency: com.apple.AppleGraphicsDeviceControl(3.20.18)[39C0D061-25CF-3D9B-815F-D99FF4E1455B]@0xffffff7f98362000
         com.apple.GeForceTesla(10.0.4)[F2D8123F-1EF8-3F6C-8C62-B2CD37544578]@0xffffff7f99125000->0xffffff7f991e3fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[F763C275-306F-358F-B6B0-0FD93486BD5F]@0xffffff7f97894000
            dependency: com.apple.iokit.IONDRVSupport(519.21)[B9EB0174-55E4-3CB1-9802-E74BB1BD5EF0]@0xffffff7f98389000
            dependency: com.apple.iokit.IOGraphicsFamily(519.23)[81D774E8-DD11-3866-B90A-E855215EDB60]@0xffffff7f9804d000
            dependency: com.apple.nvidia.classic.NVDAResmanTesla(10.0.4)[F8258F0F-61AD-30F4-BDD5-B18CCAAE535A]@0xffffff7f98eb1000

BSD process name corresponding to current thread: WindowServer

Mac OS version:
17G14042

Kernel version:
Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64
Kernel UUID: 5E83A13A-32F5-3604-8591-50E2F2F70DC6
Kernel slide:     0x0000000016e00000
Kernel text base: 0xffffff8017000000
__HIB  text base: 0xffffff8016f00000
System model name: MacBookPro6,2 (Mac-F22586C8)

System uptime in nanoseconds: 14811313154972
last loaded kext at 10081026499566: com.apple.driver.AppleUSBAudio	312.6 (addr 0xffffff7f9aa1a000, size 397312)
last unloaded kext at 9911510157843: com.apple.driver.AppleUSBAudio	312.6 (addr 0xffffff7f9a845000, size 397312)
loaded kexts:
org.virtualbox.kext.VBoxNetAdp	6.1.46
org.virtualbox.kext.VBoxNetFlt	6.1.46
org.virtualbox.kext.VBoxUSB	6.1.46
org.virtualbox.kext.VBoxDrv	6.1.46
com.radiosilenceapp.nke.filter	1
com.apple.filesystems.smbfs	3.2.3
com.apple.driver.AppleBluetoothMultitouch	92
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.filesystems.autofs	3.0
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AGPM	110.23.37
com.apple.driver.AppleMikeyHIDDriver	131
com.apple.AGDCPluginDisplayMetrics	3.20.18
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelHDGraphics	10.0.4
com.apple.driver.AppleUpstreamUserClient	3.6.5
com.apple.driver.AppleHDA	281.52
com.apple.driver.AGDCBacklightControl	3.20.18
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	6.0.7f22
com.apple.driver.pmtelemetry	1
com.apple.driver.AppleSMCPDRC	1.0.0
com.apple.driver.AppleMikeyDriver	281.52
com.apple.driver.eficheck	1
com.apple.driver.AppleIntelHDGraphicsFB	10.0.4
com.apple.GeForceTesla	10.0.4
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleMuxControl	3.20.18
com.apple.driver.SMCMotionSensor	3.0.4d1
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleSMCLMU	211
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleMCCSControl	1.5.5
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleIRController	353
com.apple.driver.AppleUSBTCKeyboard	254
com.apple.driver.AppleUSBTCButtons	254
com.apple.driver.AppleUSBCardReader	439.70.3
com.apple.filesystems.hfs.kext	407.50.6
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleSystemPolicy	1.0
com.apple.iokit.SCSITaskUserClient	404.30.3
com.apple.filesystems.apfs	748.51.0
com.apple.driver.AppleFWOHCI	5.5.9
com.apple.driver.AirPort.Brcm4331	800.21.30
com.apple.iokit.AppleBCM5701Ethernet	10.3.1
com.apple.driver.AppleAHCIPort	329.50.2
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	220.50.1
com.apple.nke.applicationfirewall	186
com.apple.security.TMSafetyNet	8
com.apple.security.quarantine	3
com.apple.driver.AppleIntelCPUPowerManagement	220.50.1
com.apple.driver.AppleUSBAudio	312.6
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.AppleBluetoothHIDKeyboard	205.1
com.apple.driver.AppleHIDKeyboard	205.1
com.apple.iokit.IOUSBUserClient	900.4.1
com.apple.driver.IOBluetoothHIDDriver	6.0.7f22
com.apple.driver.AppleMultitouchDriver	1614.1
com.apple.driver.AppleInputDeviceSupport	1614.13
com.apple.kext.triggers	1.0
com.apple.iokit.IOAVBFamily	683.1
com.apple.plugin.IOgPTPPlugin	680.15
com.apple.driver.DspFuncLib	281.52
com.apple.kext.OSvKernDSPLib	526
com.apple.driver.AppleSSE	1.0
com.apple.iokit.IOSurface	211.15
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.driver.AppleHDAController	281.52
com.apple.iokit.IOHDAFamily	281.52
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleGraphicsControl	3.20.18
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.iokit.IOFireWireIP	2.2.9
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.nvidia.classic.NVDANV50HalTesla	10.0.4
com.apple.nvidia.classic.NVDAResmanTesla	10.0.4
com.apple.AppleGPUWrangler	3.20.18
com.apple.AppleGraphicsDeviceControl	3.20.18
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IONDRVSupport	519.21
com.apple.iokit.IOGraphicsFamily	519.23
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	6.0.7f22
com.apple.iokit.IOBluetoothHostControllerUSBTransport	6.0.7f22
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.7f22
com.apple.iokit.IOBluetoothFamily	6.0.7f22
com.apple.driver.AppleUSBMultitouch	262
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.filesystems.hfs.encodings.kext	1
com.apple.iokit.IOSCSIMultimediaCommandsDevice	404.30.3
com.apple.iokit.IOBDStorageFamily	1.8
com.apple.iokit.IODVDStorageFamily	1.8
com.apple.iokit.IOCDStorageFamily	1.8
com.apple.iokit.IOFireWireFamily	4.7.2
com.apple.iokit.IOAHCISerialATAPI	267.50.1
com.apple.iokit.IOAHCIBlockStorage	301.40.2
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.usb.AppleUSBEHCIPCI	1.2
com.apple.driver.usb.AppleUSBEHCI	1.2
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.DiskImages	480.60.3
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	439.70.3
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	140.70.2
com.apple.iokit.IOSCSIBlockCommandsDevice	404.30.3
com.apple.iokit.IOSCSIArchitectureModelFamily	404.30.3
com.apple.iokit.IOStorageFamily	2.1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	31
com.apple.iokit.IOTimeSyncFamily	680.15
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

EOF
Model: MacBookPro6,2, BootROM 99.0.0.0.0, 2 processors, Intel Core i7, 2,66 GHz, 8 GB, SMC 1.58f17
Graphics: Intel HD Graphics, Intel HD Graphics, Built-In
Graphics: NVIDIA GeForce GT 330M, NVIDIA GeForce GT 330M, PCIe
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x0000, -
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x0000, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.106.98.102.30)
Bluetooth: Version 6.0.7f22, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: Samsung SSD 850 EVO 250GB, 250,06 GB
Serial ATA Device: MATSHITADVD-R   UJ-898
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Internal Memory Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus`

**Comment by Chidorin** [comment]
if i'm not mistaken the fix changes states of gpu to low power mode and there is not enough for external monitor
