### ISSUE TITLE
Doesn't work on 10.13.6 ?

### ISSUE THREAD

**Issue by Overhill93** [fabioiop/MBP-2010-GPU-Panic-fix#4]
Hi,

The app doesn't work ? When I click on the app, I just see a toothed wheel in the menu bar for 0,5 seconds, and nothing.

Do you know why ? 

Sorry for my bad English.

Thank you

**Comment by fabioiop** [comment]
yes, it’s working. 
if not working for you, you can try this others methods for 10.13.6:  [https://forums.macrumors.com/threads/gpu-kernel-panic-in-mid-2010-whats-the-best-fix.1890097/post-23312990](https://forums.macrumors.com/threads/gpu-kernel-panic-in-mid-2010-whats-the-best-fix.1890097/post-23312990)
