### ISSUE TITLE
big sur?

### ISSUE THREAD

**Issue by adamramadhan** [fabioiop/MBP-2010-GPU-Panic-fix#6]
hi im trying using this with opencore, but cant do mount -uw / as its an apfs any workaround?

**Comment by fabioiop** [comment]
Please contact the user: jackluke in this thread [macOS 11 Big Sur on Unsupported Macs Thread](https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/)
or here: [https://github.com/jacklukem/BigSurfixes](https://github.com/jacklukem/BigSurfixes)
He inserted the fix in Big Sur BaseSystem
