### ISSUE TITLE
Monterey/OCLP ?

### ISSUE THREAD

**Issue by walidbensalah** [fabioiop/MBP-2010-GPU-Panic-fix#7]
Did you manage to update this soft to Monterey ?

**Comment by fabioiop** [comment]
You can add this file to the Kext folder from the OpenCore and load it in Config.plist 
[AppleGraphicsPowerManagement.kext.zip](https://github.com/fabioiop/MBP-2010-GPU-Panic-fix/files/7685381/AppleGraphicsPowerManagement.kext.zip)

**Comment by michcio19** [comment]
Hello,

Could you explain more  how t odo this or send link to OCLP already fixed? 
When I  installed Monterey first start gpu panic and restart how to fix this? 

-Thanks

**Comment by deadiOne1** [comment]
Where to transfer it?

**Comment by ErikDeMartiis** [comment]
Hello fabioiop, I'm trying to do what you suggest.
I've mounted the EFI boot volume using OpenCore Configurator and then loaded the AppleGraphicspowerManagement.kext that you have linked in the EFI/OC/Kexts folder. Now, can you explain us how to modify the "config.plist"? EFI/EFI/OC/config.plist is the right file to modify? thank you! best regards. Erik

**Comment by fabioiop** [comment]
Try this (in Kernel - Add): 
`<dict>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>AppleGraphicsPowerManagement.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/AppleGraphicsPowerManagement</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
`
(copy and paste the attatched kext in EFI/OC/Kexts folder)
or install this kext on your OS (path: /System/Library/Extensions)
[AppleGraphicsPowerManagement.kext.zip](https://github.com/fabioiop/MBP-2010-GPU-Panic-fix/files/8905303/AppleGraphicsPowerManagement.kext.zip)

**Comment by ErikDeMartiis** [comment]
Thanks fabioiop.
I've did the modify and now I'll try to work normally to see what happen.

Can I check if what I have did is correct?
I've tried a "kextstat" from Terminal but I can't see the AppleGraphincsPowerManagement kext loaded.
Can I check in another way?

Thank you a lot :)

![plist](https://user-images.githubusercontent.com/10062040/173782428-eb99ddde-e572-4d41-8755-4655ce800c05.png)
![folder](https://user-images.githubusercontent.com/10062040/173782442-0c32d185-353e-49f8-b200-c36910795eb8.png)

**Comment by ErikDeMartiis** [comment]
Hello.
This solution seems not working :(
Any ideas? thank you very much.
Best regards
Erik

**Comment by fabioiop** [comment]
It's definitely working.

![Screen Shot](https://user-images.githubusercontent.com/12833208/174601655-bf6c0c3b-b737-4115-b7d1-0c9bfff4e6c3.png)


My last tip that will be able to help you:
remove the AGPM-override and AppleGraphicsPowerManagement kexts and plist entries for both from OCLP.
Dowload this app (works in monterey) (special thanks to friend  [https://github.com/jacklukem](url) ). 
Run and select the Monterey system volume. Paste the AppleGraphicsPowerManagement into the /System/Library/Extensions folder (back up the default kext). Rebuild KC button. Reboot

[BigSurmountsrw2.zip](https://github.com/fabioiop/MBP-2010-GPU-Panic-fix/files/8940583/BigSurmountsrw2.zip)
[AppleGraphicsPowerManagement.kext.zip](https://github.com/fabioiop/MBP-2010-GPU-Panic-fix/files/8940587/AppleGraphicsPowerManagement.kext.zip) (same as attached above.)

**Comment by ErikDeMartiis** [comment]
> It's definitely working.
> 

I can confirm that now the Kext is loaded.
I've 2 AppleGraphicsPowerManagement kexts, one loaded "v119" and one not loaded  v"127" (maybe from another experiment, then I'll try to delete it).

Now I'll stress the MacBook to test if all is working. Thank you and Jackluken for the support!
best regards
Erik

**Comment by ErikDeMartiis** [comment]
First of all, thank you very much,
Now, I can confirm that all is working. My MacBook Pro not PANIC anymore.  I'm using it in a developing session with Xcode, Simulators, Numbers, phpMyadmin, Mail, Safari, Note, Message, Preview, Sublime Text, all opened. I've stopped and slipped the Mac without any problem. So, now a line for the search engines: this fabioiop & jackluken patch is working on Monterey on MacBook Pro 6,2 and resolve kernel panic issue.

**Comment by fabioiop** [comment]
> First of all, thank you very much, Now, I can confirm that all is working. My MacBook Pro not PANIC anymore. I'm using it in a developing session with Xcode, Simulators, Numbers, phpMyadmin, Mail, Safari, Note, Message, Preview, Sublime Text, all opened. I've stopped and slipped the Mac without any problem. So, now a line for the search engines: this fabioiop & jackluken patch is working on Monterey on MacBook Pro 6,2 and resolve kernel panic issue.

Great! 
Thank you about report

**Comment by iDerekUA** [comment]
Yes, it works. Thank you

**Comment by franzose** [comment]
Thank you very much for the tool! It looks like it has helped on my macOS High Sierra.

**Comment by Alvarolopezgt** [comment]
What version of OCLP is used to do this?

**Comment by ghost1255** [comment]
hi guys i have the famous macbook pro mid 2010 i bypassed the gpu by doing the fix i want to install macOS monterey can anyone help me please
