### ISSUE TITLE
Can't restore previous config

### ISSUE THREAD

**Issue by miniarmagb** [fabioiop/MBP-2010-GPU-Panic-fix#8]
This is what the console displays and I've run the patcher and restarted but I'm unable to restore.

` | Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | macOS version : 
 macOS 10.13
  | Checking SIP Status
 SIP Disabled
 `

**Comment by fabioiop** [comment]
I think you used this one: [https://github.com/julian-poidevin/MBPMid2010_GPUFix](url)
