### ISSUE TITLE
Windows (BootCamp)

### ISSUE THREAD

**Issue by deadiOne1** [fabioiop/MBP-2010-GPU-Panic-fix#9]
Is it possible to make this program on a Windows system?  I usually use Windows BootCamp on this laptop and there is also such a problem, I would be very grateful if it works somehow

**Comment by fabioiop** [comment]
No, this one only works for macOS.
Try underclocking the GPU to 249mhz (maximum value).

**Comment by deadiOne1** [comment]
Oh, sorry, but how to do it?

**Comment by deadiOne1** [comment]
https://github.com/fabioiop/MBP-2010-GPU-Panic-fix/issues/9#issuecomment-1144746157

**Comment by deadiOne1** [comment]
Oh, sorry, but how is that?

**Comment by fabioiop** [comment]
search google for some overclock tweak tool for nvidia
